// packages/cli/templates/vue3/src/components/AssetSelector.vue
<script setup lang="ts">
import { ref } from 'vue'
import { PluginActions, PluginState } from '@storyblok/field-plugin'

const props = defineProps<{
  selectAsset: PluginActions['selectAsset']
  data: PluginState
}>()

const imageUrl = ref('')

const handleSelectAsset = async () => {
  imageUrl.value = await props.selectAsset()
}

const removeAsset = async () => {
  imageUrl.value = ''
}
</script>

<template>
  <div class="asset-selector">
    <h2>Asset Selector</h2>
    <img
      :src="imageUrl"
      v-if="imageUrl"
    />
    <button
      v-if="imageUrl"
      class="btn w-full"
      @click="removeAsset"
    >
      Remove Asset
    </button>
    <button
      v-else
      class="btn w-full"
      @click="handleSelectAsset"
    >
      Select Asset
    </button>
  </div>
</template>

// packages/cli/templates/react/src/components/AssetSelector.tsx
import { useState } from 'react'
import { PluginActions } from '@storyblok/field-plugin'

type Props = {
  selectAsset: PluginActions['selectAsset']
}
const AssetSelector = ({ selectAsset }: Props) => {
  const [imageUrl, setImageUrl] = useState<string>('')

  const handleSelectAsset = async () => {
    setImageUrl(await selectAsset())
  }

  const removeAsset = async () => {
    setImageUrl('')
  }

  return (
    <div className="asset-selector">
      <h2>Asset Selector</h2>
      {imageUrl && (
        <img
          src={imageUrl}
          title="Selected Asset"
        />
      )}
      {imageUrl && (
        <button
          className="btn w-full"
          onClick={removeAsset}
        >
          Remove Asset
        </button>
      )}
      {!imageUrl && (
        <button
          className="btn w-full"
          onClick={handleSelectAsset}
        >
          Select Asset
        </button>
      )}
    </div>
  )
}

export default AssetSelector
