// packages/cli/templates/vue2/src/components/AssetSelector.vue
<template>
  <div class="asset-selector">
    <h2>Asset Selector</h2>
    <img
      v-if="asset"
      :src="asset.filename"
      title="Selected Asset"
    />
    <button
      v-if="asset"
      class="btn w-full"
      @click="removeAsset"
    >
      Remove Asset
    </button>
    <button
      v-else
      class="btn w-full"
      @click="handleSelectAsset"
    >
      Select Asset
    </button>
  </div>
</template>

<script>
export default {
  inject: ['plugin'],
  data() {
    return {
      asset: undefined,
    }
  },
  methods: {
    async handleSelectAsset() {
      this.asset.value = await this.plugin.actions.selectAsset()
    },
    removeAsset() {
      this.asset.value = undefined
    },
  },
}
</script>

// packages/cli/templates/react/src/components/AssetSelector.tsx
import { FunctionComponent, useState } from 'react'
import { useFieldPlugin } from '../useFieldPlugin'
import { Asset } from '@storyblok/field-plugin'

const AssetSelector: FunctionComponent = () => {
  const {
    actions: { selectAsset },
  } = useFieldPlugin()

  const [asset, setAsset] = useState<Asset | undefined>()

  const handleSelectAsset = async () => {
    setAsset(await selectAsset())
  }

  const removeAsset = async () => {
    setAsset(undefined)
  }

  return (
    <div className="asset-selector">
      <h2>Asset Selector</h2>
      {asset && (
        <img
          src={asset.filename}
          title="Selected Asset"
        />
      )}
      {asset && (
        <button
          className="btn w-full"
          onClick={removeAsset}
        >
          Remove Asset
        </button>
      )}
      {!asset && (
        <button
          className="btn w-full"
          onClick={handleSelectAsset}
        >
          Select Asset
        </button>
      )}
    </div>
  )
}

export default AssetSelector
