// packages/cli/templates/react/src/components/Counter.tsx
import { FunctionComponent } from 'react'
import { useFieldPlugin } from '../useFieldPlugin'

const Counter: FunctionComponent = () => {
  const { data, actions } = useFieldPlugin()

  const label = typeof data.value !== 'number' ? 0 : JSON.stringify(data.value)
  const handleIncrement = () => {
    actions.setValue((typeof data.value === 'number' ? data.value : 0) + 1)
  }

  return (
    <div>
      <h2>Field Value</h2>
      <div className="counter-value">{label}</div>
      <button
        className="btn w-full"
        onClick={handleIncrement}
      >
        Increment
      </button>
    </div>
  )
}

export default Counter

// packages/cli/templates/vue3/src/components/Counter.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useFieldPlugin } from '../useFieldPlugin'

const plugin = useFieldPlugin()

const handleIncrement = () => {
  const value = plugin.data.value
  plugin.actions.setValue((typeof value === 'number' ? value : 0) + 1)
}

const label = computed(() => {
  const value = plugin.data.value
  return typeof value !== 'number' ? 0 : JSON.stringify(value)
})
</script>

<template>
  <div>
    <h2>Field Value</h2>
    <div class="counter-value">
      {{ label }}
    </div>
    <button
      class="btn w-full"
      @click="handleIncrement"
    >
      Increment
    </button>
  </div>
</template>
