// packages/field-plugin/helpers/react/src/FieldPluginProvider.tsx
import { ComponentType, FunctionComponent, useEffect, useState } from 'react'
import {
  createFieldPlugin,
  type FieldPluginResponse,
} from '@storyblok/field-plugin'
import { FieldPluginContext } from './FieldPluginContext'
import { ReactNode } from 'react'

type Props = {
  Error?: ComponentType<{ error: Error }>
  Loading?: ComponentType
  children?: ReactNode
}

export const FieldPluginProvider: FunctionComponent<Props> = ({
  Error,
  Loading,
  children,
}) => {
  const [state, setState] = useState<FieldPluginResponse>({
    type: 'loading',
  })

  useEffect(() => createFieldPlugin(setState), [])

  if (state.type === 'loading') {
    return Loading ? <Loading /> : <></>
  } else if (state.type === 'error') {
    return Error ? <Error error={state.error} /> : <></>
  } else {
    return (
      <FieldPluginContext.Provider value={state}>
        {children}
      </FieldPluginContext.Provider>
    )
  }
}

// packages/cli/templates/vue3/src/components/FieldPluginProvider.vue
<script setup lang="ts">
import { provide, reactive } from 'vue'
import { createFieldPlugin, FieldPluginResponse } from '@storyblok/field-plugin'

const plugin = reactive<FieldPluginResponse>({
  type: 'loading',
})
createFieldPlugin((newState) => {
  plugin.type = newState.type
  plugin.error = newState.error
  plugin.data = newState.data
  plugin.actions = newState.actions
})
provide('field-plugin', plugin)
</script>

<template>
  <slot
    name="loading"
    v-if="plugin.type === 'loading'"
  ></slot>
  <slot
    name="error"
    v-if="plugin.type === 'error'"
  ></slot>
  <slot v-if="plugin.type === 'loaded'"></slot>
</template>
