// packages/cli/templates/react/src/components/FieldPluginExample/AssetSelector.tsx
import { FunctionComponent, useState } from 'react'
import type { Asset, SelectAsset } from '@storyblok/field-plugin'

const AssetSelector: FunctionComponent<{ selectAsset: SelectAsset }> = ({
  selectAsset,
}) => {
  const [asset, setAsset] = useState<Asset | undefined>()

  const handleSelectAsset = async () => {
    setAsset(await selectAsset())
  }

  const removeAsset = async () => {
    setAsset(undefined)
  }

  return (
    <div className="asset-selector">
      <h2>Asset Selector</h2>
      {asset && (
        <img
          src={asset.filename}
          title="Selected Asset"
        />
      )}
      {asset && (
        <button
          className="btn w-full"
          onClick={removeAsset}
        >
          Remove Asset
        </button>
      )}
      {!asset && (
        <button
          className="btn w-full"
          onClick={handleSelectAsset}
        >
          Select Asset
        </button>
      )}
    </div>
  )
}

export default AssetSelector

// packages/cli/templates/vue2/src/components/FieldPluginExample/AssetSelector.vue
<template>
  <div class="asset-selector">
    <h2>Asset Selector</h2>
    <img v-if="asset" :src="asset.filename" title="Selected Asset" />
    <button v-if="asset" class="btn w-full" @click="removeAsset">
      Remove Asset
    </button>
    <button v-else class="btn w-full" @click="handleSelectAsset">
      Select Asset
    </button>
  </div>
</template>

<script>
export default {
  props: ['selectAsset'],
  data() {
    return {
      asset: undefined,
    }
  },
  methods: {
    async handleSelectAsset() {
      this.asset = await this.selectAsset()
    },
    removeAsset() {
      this.asset = undefined
    },
  },
}
</script>
