// packages/cli/templates/react/src/components/AssetSelector.tsx
import { FunctionComponent, useState } from 'react'
import { useFieldPlugin } from '../useFieldPlugin'
import { Asset } from '@storyblok/field-plugin'

const AssetSelector: FunctionComponent = () => {
  const {
    actions: { selectAsset },
  } = useFieldPlugin()

  const [asset, setAsset] = useState<Asset | undefined>()

  const handleSelectAsset = async () => {
    setAsset(await selectAsset())
  }

  const removeAsset = async () => {
    setAsset(undefined)
  }

  return (
    <div className="asset-selector">
      <h2>Asset Selector</h2>
      {asset && (
        <img
          src={asset.filename}
          title="Selected Asset"
        />
      )}
      {asset && (
        <button
          className="btn w-full"
          onClick={removeAsset}
        >
          Remove Asset
        </button>
      )}
      {!asset && (
        <button
          className="btn w-full"
          onClick={handleSelectAsset}
        >
          Select Asset
        </button>
      )}
    </div>
  )
}

export default AssetSelector

// packages/cli/templates/vue3/src/components/FieldPluginExample/AssetSelector.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useFieldPlugin } from '../../useFieldPlugin'
import { Asset } from '@storyblok/field-plugin'

const plugin = useFieldPlugin()

const asset = ref<Asset>()

const handleSelectAsset = async () => {
  asset.value = await plugin.actions.selectAsset()
}

const removeAsset = () => {
  asset.value = undefined
}
</script>

<template>
  <div class="asset-selector">
    <h2>Asset Selector</h2>
    <img
      v-if="asset"
      :src="asset.filename"
      title="Selected Asset"
    />
    <button
      v-if="asset"
      class="btn w-full"
      @click="removeAsset"
    >
      Remove Asset
    </button>
    <button
      v-else
      class="btn w-full"
      @click="handleSelectAsset"
    >
      Select Asset
    </button>
  </div>
</template>
