// packages/cli/templates/react/src/components/Counter.tsx
import { FunctionComponent } from 'react'
import { useFieldPlugin } from '../useFieldPlugin'

const Counter: FunctionComponent = () => {
  const {
    data,
    actions: { setContent },
  } = useFieldPlugin()

  const label =
    typeof data.content !== 'number' ? 0 : JSON.stringify(data.content)
  const handleIncrement = () => {
    setContent((typeof data.content === 'number' ? data.content : 0) + 1)
  }

  return (
    <div>
      <h2>Field Value</h2>
      <div className="counter-value">{label}</div>
      <button
        className="btn w-full"
        onClick={handleIncrement}
      >
        Increment
      </button>
    </div>
  )
}

export default Counter

// packages/cli/templates/vue3/src/components/FieldPluginExample/Counter.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useFieldPlugin } from '../../useFieldPlugin'

const plugin = useFieldPlugin()

const handleIncrement = () => {
  const content = plugin.data.content
  plugin.actions.setContent((typeof content === 'number' ? content : 0) + 1)
}

const label = computed(() => {
  const content = plugin.data.content
  return typeof content !== 'number' ? 0 : JSON.stringify(content)
})
</script>

<template>
  <div>
    <h2>Field Value</h2>
    <div class="counter-value">
      {{ label }}
    </div>
    <button
      class="btn w-full"
      @click="handleIncrement"
    >
      Increment
    </button>
  </div>
</template>
