// packages/cli/templates/react/src/components/ModalToggle.tsx
import { FunctionComponent } from 'react'
import { useFieldPlugin } from '../useFieldPlugin'

const ModalToggle: FunctionComponent = () => {
  const {
    data: { isModalOpen },
    actions: { setModalOpen },
  } = useFieldPlugin()

  return (
    <div>
      <h2>Modal</h2>
      <button
        className="btn w-full"
        type="button"
        onClick={() => setModalOpen(!isModalOpen)}
      >
        {isModalOpen ? 'Close' : 'Open'} modal
      </button>
    </div>
  )
}

export default ModalToggle

// packages/cli/templates/vue3/src/components/FieldPluginExample/ModalToggle.vue
<script setup lang="ts">
import { useFieldPlugin } from '../../useFieldPlugin'

const plugin = useFieldPlugin()
</script>

<template>
  <div>
    <h2>Modal</h2>
    <button
      class="btn w-full"
      type="button"
      @click="() => plugin.actions.setModalOpen(!plugin.data.isModalOpen)"
    >
      {{ plugin.data.isModalOpen ? 'Close' : 'Open' }} modal
    </button>
  </div>
</template>
