// packages/cli/templates/vue2/src/components/FieldPluginExample/ModalToggle.vue
<template>
  <div>
    <h2>Modal</h2>
    <button
      class="btn w-full"
      type="button"
      @click="() => setModalOpen(!isModalOpen)"
    >
      {{ isModalOpen ? 'Close' : 'Open' }} modal
    </button>
  </div>
</template>

<script>
export default {
  props: ['isModalOpen', 'setModalOpen'],
}
</script>

// packages/cli/templates/react/src/components/FieldPluginExample/ModalToggle.tsx
import { FunctionComponent } from 'react'

const ModalToggle: FunctionComponent<{
  isModalOpen: boolean
  setModalOpen: (isModalOpen: boolean) => void
}> = ({ isModalOpen, setModalOpen }) => {
  return (
    <div>
      <h2>Modal</h2>
      <button
        className="btn w-full"
        type="button"
        onClick={() => setModalOpen(!isModalOpen)}
      >
        {isModalOpen ? 'Close' : 'Open'} modal
      </button>
    </div>
  )
}

export default ModalToggle
