// packages/cli/templates/vue3/src/components/ModalToggle.vue
<script setup lang="ts">
import { defineProps } from 'vue'
import { PluginActions, PluginState } from '@storyblok/field-plugin'

defineProps<{
  actions: PluginActions
  data: PluginState
}>()
</script>

<template>
  <div class="modal-toggle">
    <button
      type="button"
      @click="() => actions.setModalOpen(!data.isModalOpen)"
    >
      {{ data.isModalOpen ? 'Close' : 'Open' }} modal
    </button>
  </div>
</template>

// packages/demo/src/components/ModalToggle.tsx
import { Button, Stack, Typography } from '@mui/material'
import { PluginComponent } from './FieldPluginDemo'

export const ModalToggle: PluginComponent = (props) => {
  const { actions, data } = props
  return (
    <Stack gap={2}>
      <Typography variant="subtitle1">Modal</Typography>
      <Button
        variant="outlined"
        color="secondary"
        onClick={() => actions.setModalOpen(!data.isModalOpen)}
      >
        Toggle Modal
      </Button>
    </Stack>
  )
}
