// packages/cli/templates/react/src/components/FieldPluginExample/Counter.tsx
import { FunctionComponent } from 'react'
import { useFieldPlugin } from '@storyblok/field-plugin/react'

const Counter: FunctionComponent = () => {
  const {
    data,
    actions: { setContent },
  } = useFieldPlugin()

  const label =
    typeof data.content !== 'number' ? 0 : JSON.stringify(data.content)
  const handleIncrement = () => {
    setContent((typeof data.content === 'number' ? data.content : 0) + 1)
  }

  return (
    <div>
      <h2>Field Value</h2>
      <div className="counter-value">{label}</div>
      <button
        className="btn w-full"
        onClick={handleIncrement}
      >
        Increment
      </button>
    </div>
  )
}

export default Counter

// packages/cli/templates/vue2/src/components/Counter.vue
<template>
  <div>
    <h2>Field Value</h2>
    <div class="counter-value">
      {{ label }}
    </div>
    <button
      class="btn w-full"
      @click="handleIncrement"
    >
      Increment
    </button>
  </div>
</template>

<script>
export default {
  inject: ['plugin'],
  computed: {
    label() {
      const content = this.plugin.data.content
      return typeof content !== 'number' ? 0 : JSON.stringify(content)
    },
  },
  methods: {
    handleIncrement() {
      const content = this.plugin.data.content
      this.plugin.actions.setContent(
        (typeof content === 'number' ? content : 0) + 1,
      )
    },
  },
}
</script>
