// packages/cli/templates/vue3/src/App.vue
<script setup lang="ts">
import { useFieldPlugin } from './useFieldPlugin'
import FieldPlugin from './components/FieldPlugin.vue'

const plugin = useFieldPlugin()
</script>

<template>
  <span v-if="plugin.type === 'loading'">Loading...</span>
  <span v-else-if="plugin.type === 'error'">Error</span>
  <FieldPlugin
    v-else-if="plugin.type === 'loaded'"
    :data="plugin.data"
    :actions="plugin.actions"
  />
</template>

// packages/cli/templates/react/src/App.tsx
import { useFieldPlugin } from './useFieldPlugin'
import FieldPlugin from './components/FieldPlugin'

function App() {
  const { type, data, actions } = useFieldPlugin()

  if (type === 'loading') {
    return <span>Loading...</span>
  }

  if (type === 'error') {
    return <span>Error</span>
  }

  return type === 'loaded' ? (
    <FieldPlugin
      data={data}
      actions={actions}
    />
  ) : null
}

export default App
