// packages/cli/templates/vue2/src/components/FieldPluginProvider.vue
<template>
  <div class="field-plugin-provider">
    <slot
      name="loading"
      v-if="plugin.type === 'loading'"
    ></slot>
    <slot
      name="error"
      v-if="plugin.type === 'error'"
    ></slot>
    <slot v-if="plugin.type === 'loaded'"></slot>
  </div>
</template>

<script>
import { createFieldPlugin } from '@storyblok/field-plugin'
import Vue from 'vue'

const plugin = Vue.observable({
  type: 'loading',
})

createFieldPlugin((newState) => {
  Vue.set(plugin, 'type', newState.type)
  Vue.set(plugin, 'error', newState.error)
  Vue.set(plugin, 'data', newState.data)
  Vue.set(plugin, 'actions', newState.actions)
})

export default {
  provide: {
    plugin,
  },
  data() {
    return { plugin }
  },
}
</script>
<style scoped>
.field-plugin-provider {
  width: 100%;
}
</style>

// packages/cli/templates/react/src/FieldPluginProvider.tsx
import {
  FunctionComponent,
  createContext,
  useEffect,
  useState,
  ComponentType,
} from 'react'
import {
  type FieldPluginResponse,
  createFieldPlugin,
} from '@storyblok/field-plugin'
import { ReactNode } from 'react'

export const FieldPluginContext = createContext<
  Extract<FieldPluginResponse, { type: 'loaded' }> | undefined
>(undefined)

type Props = {
  Error?: ComponentType<{ error: Error }>
  Loading?: ComponentType
  children?: ReactNode
}

export const FieldPluginProvider: FunctionComponent<Props> = ({
  Error,
  Loading,
  children,
}) => {
  const [state, setState] = useState<FieldPluginResponse>({
    type: 'loading',
  })

  useEffect(() => createFieldPlugin(setState), [])

  if (state.type === 'loading') {
    return Loading ? <Loading /> : <></>
  } else if (state.type === 'error') {
    return Error ? <Error error={state.error} /> : <></>
  } else {
    return (
      <FieldPluginContext.Provider value={state}>
        {children}
      </FieldPluginContext.Provider>
    )
  }
}
